
gems: [jekyll-paginate]
paginate: 9
paginate_path: "/blog/page:num/"

title: Your awesome title
name: Oqueber Navarro
# Short bio or description (displayed in the header)
email: oqueber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola soy oqueber
# cuentanos sobre ti:
baseurl: "" # the subpath of your site, e.g. /blog
url: "oqueber.github.io" # the base hostname & protocol for your site
permalink: /:title/

google_analytics: UA-82888756-1
#-------------------------------------------------------------------------------------------------------------------------
#Espacio de trabajo -1-
work-1-link: /blog
#-- La imagen debe de estar en la carpeta img y colocas el nombre y el tipo(.jpg o .png)
work-1-nombreImagen: 1.jpg
work-1-descriptionImagen: ejemlo de work1
work-1-Titulo: Mi trabajo fue probar
# Espacio de trabajo -2-
work-2-link: /blog
#-- La imagen debe de estar en la carpeta img y colocas el nombre y el tipo(.jpg o .png)
work-2-nombreImagen: 2.jpg
work-2-descriptionImagen: ejemlo de work2
work-2-Titulo: Mi trabajo fue probar
# Espacio de trabajo -3-
work-3-link: /blog
#-- La imagen debe de estar en la carpeta img y colocas el nombre y el tipo(.jpg o .png)
work-3-nombreImagen: 3.jpg
work-3-descriptionImagen: ejemlo de work3
work-3-Titulo: Mi trabajo fue probar
#-----------------------------------------------------------------------------------------------------------------------------
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: oqueer_2324@hotmai.com
  facebook: oqueber.navarro
  github: oqueber
  instagram:
  linkedin:
  pinterest:
  twitter: oqueber_n
  youtube: # channel/<your_long_string> or user/<user-name>

# Build settings
markdown: kramdown
theme: minima
