
gems: [jekyll-paginate]
paginate: 9
paginate_path: "/blog/page:num/"

title: Your awesome title
name: Oqueber Navarro
# Short bio or description (displayed in the header)
email: oqueber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola soy oqueber
# cuentanos sobre ti:
aboutMe: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.<br><br>No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.

baseurl: "" # the subpath of your site, e.g. /blog
url: "oqueber.github.io" # the base hostname & protocol for your site
permalink: /:title/


#-------------------------------------------------------------------------------------------------------------------------
# Carta numero #1 del timeline
carta-1-date: 1996
carta-1-color: purplue
carta-1-title: Nacimiento
carta-1-description:  Yo soy el mega parrafo de la cata 1
# Carta numero #2 del timeline
carta-2-date: 2000
carta-2-color: purplue
carta-2-title: Termine la Primaria
carta-2-description: Yo soy yo y no creo en nadie, pues es un peo todo y tu sabes pues.
# Carta numero #3 del timeline
carta-3-date: 2010
carta-3-color: orange
carta-3-title: Termine la sengundaria
carta-3-description: No lo se agrega cualquier vaina
# Carta numero #4 del timeline
carta-4-date: 2012
carta-4-color: purplue
carta-4-title: Empece mis estudios en la UPTA
carta-4-description: Esa universidad fue una mierda.
# Carta numero #5 del timeline
carta-5-date: 2014
carta-5-color: purplue
carta-5-title: Empece en la prestigiosa USB
carta-5-description: Hola no lo se
# Carta numero #6 del timeline
carta-6-date: 2014
carta-6-color: orange
carta-6-title: Empece en la prestigiosa USB
carta-6-description: Hola no lo se
#-------------------------------------------------------------------------------------------------------------------------
#Espacio de trabajo -1-
work-1-link: /blog
#-- La imagen debe de estar en la carpeta img y colocas el nombre y el tipo(.jpg o .png)
work-1-nombreImagen: 1.jpg
work-1-descriptionImagen: ejemlo de work1
work-1-Titulo: Mi trabajo fue probar
# Espacio de trabajo -2-
work-2-link: /blog
#-- La imagen debe de estar en la carpeta img y colocas el nombre y el tipo(.jpg o .png)
work-2-nombreImagen: 2.jpg
work-2-descriptionImagen: ejemlo de work2
work-2-Titulo: Mi trabajo fue probar
# Espacio de trabajo -3-
work-3-link: /blog
#-- La imagen debe de estar en la carpeta img y colocas el nombre y el tipo(.jpg o .png)
work-3-nombreImagen: 3.jpg
work-3-descriptionImagen: ejemlo de work3
work-3-Titulo: Mi trabajo fue probar
#-----------------------------------------------------------------------------------------------------------------------------
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: oqueer_2324@hotmai.com
  facebook: oqueber.navarro
  github: oqueber
  instagram:
  linkedin:
  pinterest:
  twitter: oqueber_n
  youtube: # channel/<your_long_string> or user/<user-name>

# Build settings
markdown: kramdown
theme: minima
