# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Oqueber Navarro
title: Oqueber Navarro
description: Sitio web personal
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
permalink: /:title/

google_analytics: UA-82888756-1

gems: [jekyll-sitemap,jekyll-paginate, jekyll-seo-tag]

paginate: 9
paginate_path: "/blog/page:num/"

# Botones para el footer
footer-links:
  dribbble:
  email: oqueer_2324@hotmai.com
  facebook: oqueber.navarro
  github: oqueber
  instagram:
  linkedin:
  pinterest:
  twitter: oqueber_n
  youtube: # channel/<your_long_string> or user/<user-name>

# Build settings
markdown: kramdown
theme: minima
